"use client";

import { useEffect, useMemo, useState } from "react";
import { useLang } from "@/context/LangContext";
import type { TakeawayCatalogItem } from "@/lib/takeaway/types";
import { formatEuro } from "@/lib/takeaway/format";

export interface Customization { choiceIds: string[]; specialInstructions: string; unitPrice: number }

export default function TakeawayItemCustomizer({ item, onClose, onAdd }: { item: TakeawayCatalogItem; onClose: () => void; onAdd: (value: Customization) => void }) {
  const { t, lang } = useLang();
  const [selected, setSelected] = useState<string[]>(() => item.option_groups.flatMap((group) => group.choices?.filter((choice) => choice.is_available && choice.is_default).slice(0, group.max_selections).map((choice) => choice.id) ?? []));
  const [instructions, setInstructions] = useState("");
  useEffect(() => { document.body.style.overflow = "hidden"; (window as any).lenis?.stop(); return () => { document.body.style.overflow = ""; (window as any).lenis?.start(); }; }, []);
  const unitPrice = useMemo(() => Math.max(0, Number(item.price) + item.option_groups.flatMap((group) => group.choices ?? []).filter((choice) => selected.includes(choice.id)).reduce((sum, choice) => sum + Number(choice.price_modifier), 0)), [item, selected]);
  const valid = item.option_groups.every((group) => { const count = group.choices?.filter((choice) => selected.includes(choice.id)).length ?? 0; return count >= group.min_selections && count <= group.max_selections; });
  const clearGroup = (groupId: string) => { const group = item.option_groups.find((value) => value.id === groupId); const ids = new Set(group?.choices?.map((choice) => choice.id)); setSelected((current) => current.filter((id) => !ids.has(id))); };
  const toggle = (groupId: string, choiceId: string) => { const group = item.option_groups.find((value) => value.id === groupId); const choice = group?.choices?.find((value) => value.id === choiceId); if (!group || !choice?.is_available) return; const groupIds = new Set(group.choices?.map((value) => value.id)); const inGroup = selected.filter((id) => groupIds.has(id)); if (selected.includes(choiceId)) setSelected((current) => current.filter((id) => id !== choiceId)); else if (group.selection_type === "single") setSelected((current) => [...current.filter((id) => !groupIds.has(id)), choiceId]); else if (inGroup.length < group.max_selections) setSelected((current) => [...current, choiceId]); };
  return <div className="fixed inset-0 z-[100] grid place-items-end bg-black/60 md:place-items-center" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section data-lenis-prevent="true" className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl border border-theme bg-surface p-6 md:max-w-xl md:rounded-3xl"><button className="float-right text-fg" onClick={onClose} aria-label={t({ fr: "Fermer", en: "Close", es: "Cerrar", it: "Chiudi" })}>×</button><h2 className="text-3xl text-fg">{item.name}</h2><p className="mt-2 text-sm text-fg/60">{item.description}</p><div className="my-5 space-y-5">{item.option_groups.map((group) => <fieldset key={group.id}><legend className="mb-2 text-fg">{group.name[lang]} <small className="text-fg/45">({group.min_selections}–{group.max_selections})</small></legend><div className="grid gap-2">{group.selection_type === "single" && group.min_selections === 0 ? <label className="flex items-center rounded-xl border border-theme p-3 text-fg"><input className="mr-2" type="radio" name={group.id} checked={!group.choices?.some((choice) => selected.includes(choice.id))} onChange={() => clearGroup(group.id)} />{t({ fr: "Aucun", en: "None", es: "Ninguno", it: "Nessuno" })}</label> : null}{group.choices?.map((choice) => <label key={choice.id} className={`flex items-center justify-between rounded-xl border border-theme p-3 ${choice.is_available ? "text-fg" : "cursor-not-allowed text-fg/40"}`}><span><input className="mr-2" disabled={!choice.is_available} type={group.selection_type === "single" ? "radio" : "checkbox"} name={group.id} checked={selected.includes(choice.id)} onChange={() => toggle(group.id, choice.id)} />{choice.name[lang]} {!choice.is_available ? <small className="ml-2 text-red-400">{t({ fr: "Épuisé", en: "Sold out", es: "Agotado", it: "Esaurito" })}</small> : null}</span><span>{Number(choice.price_modifier) > 0 ? "+" : ""}{formatEuro(Number(choice.price_modifier), lang)}</span></label>)}</div></fieldset>)}</div><textarea maxLength={300} className="w-full rounded-xl border border-theme bg-bg p-3 text-fg" value={instructions} onChange={(e) => setInstructions(e.target.value)} placeholder={t({ fr: "Instructions spéciales", en: "Special instructions", es: "Instrucciones especiales", it: "Istruzioni speciali" })} /><button disabled={!valid} onClick={() => onAdd({ choiceIds: [...selected].sort(), specialInstructions: instructions.trim(), unitPrice })} className="mt-4 w-full rounded-xl bg-fg p-4 text-bg disabled:opacity-40">{t({ fr: "Ajouter", en: "Add", es: "Añadir", it: "Aggiungi" })} — {formatEuro(unitPrice, lang)}</button></section></div>;
}
