"use client";

import { useLang } from "@/context/LangContext";
import { formatEuro } from "@/lib/takeaway/format";
type DocketOrder = { order_reference: string; customer_name: string; customer_phone: string; pickup_time: string; payment_status: string; final_total_ttc: number; order_snapshot: { customer?: { notes?: string }; items?: { quantity: number; name: string; selected_options?: { group_name: Record<string, string> | string; choice_name: Record<string, string> | string }[] }[] } };

export default function TakeawayKitchenDocket({ order }: { order: DocketOrder }) {
  const { t, lang } = useLang(); const label = (value: Record<string, string> | string) => typeof value === "string" ? value : value[lang] ?? value.fr ?? value.en;
  return <div className="takeaway-docket print-target hidden"><h1>L’ÉCHOPPE DE PARIS</h1><h2>{t({ fr: "BON DE CUISINE", en: "KITCHEN DOCKET", es: "COMANDA DE COCINA", it: "COMANDA CUCINA" })}</h2><hr /><p>{t({ fr: "COMMANDE", en: "ORDER", es: "PEDIDO", it: "ORDINE" })} : #{order.order_reference}<br />{t({ fr: "RETRAIT", en: "PICKUP", es: "RECOGIDA", it: "RITIRO" })} : {new Date(order.pickup_time).toLocaleString(lang, { timeZone: "Europe/Paris" })}<br />{t({ fr: "CLIENT", en: "CUSTOMER", es: "CLIENTE", it: "CLIENTE" })} : {order.customer_name}<br />{t({ fr: "TÉL", en: "PHONE", es: "TEL", it: "TEL" })} : {order.customer_phone}</p><hr />{order.order_snapshot.items?.map((item, index) => <div key={index}><strong>{item.quantity}× {item.name}</strong>{item.selected_options?.map((option, optionIndex) => <p key={optionIndex}>- {label(option.group_name)} : {label(option.choice_name)}</p>)}</div>)}{order.order_snapshot.customer?.notes ? <><hr /><p>{t({ fr: "NOTE CLIENT", en: "CUSTOMER NOTE", es: "NOTA DEL CLIENTE", it: "NOTA CLIENTE" })} :<br />{order.order_snapshot.customer.notes}</p></> : null}<hr /><p><strong>{t({ fr: "TOTAL À ENCAISSER", en: "TOTAL DUE", es: "TOTAL A COBRAR", it: "TOTALE DA INCASSARE" })} : {formatEuro(Number(order.final_total_ttc), lang)}</strong><br />[{order.payment_status === "PAID" ? t({ fr: "PAYÉ", en: "PAID", es: "PAGADO", it: "PAGATO" }) : t({ fr: "NON PAYÉ", en: "UNPAID", es: "NO PAGADO", it: "NON PAGATO" })}]</p></div>;
}
