"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { useLang } from "@/context/LangContext";
import type { Category } from "@/lib/hooks/useCategories";
import { categoryLabel } from "@/lib/takeaway/categoryPresentation";
import { formatEuro } from "@/lib/takeaway/format";
import { findDeepLinkedItem } from "@/lib/takeaway/orderRules";
import type { PublicTakeawayConfig, TakeawayCatalogItem } from "@/lib/takeaway/types";
import TakeawayItemCustomizer, { type Customization } from "./TakeawayItemCustomizer";

type Slot = { value: string; type: "asap" | "scheduled"; available: boolean };
type Props = { onAdd?: (item: TakeawayCatalogItem, customization: Customization) => void; onOpenCart: () => void; cartCount: number; cartTotal: number; added: boolean };

export default function TakeawayMenu({ onAdd, onOpenCart, cartCount, cartTotal, added }: Props) {
  const { t, lang } = useLang();
  const [config, setConfig] = useState<PublicTakeawayConfig | null>(null); const [items, setItems] = useState<TakeawayCatalogItem[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [active, setActive] = useState(""); const [customizing, setCustomizing] = useState<TakeawayCatalogItem | null>(null); const [slots, setSlots] = useState<Slot[]>([]); const [error, setError] = useState(false);
  useEffect(() => { void Promise.all([fetch("/api/takeaway/config", { cache: "no-store" }), fetch("/api/takeaway/menu", { cache: "no-store" }), fetch("/api/takeaway/slots", { cache: "no-store" })]).then(async ([configResponse, menuResponse, slotResponse]) => { if (!configResponse.ok || !menuResponse.ok) throw new Error(); const [configuration, menu, slotData] = await Promise.all([configResponse.json(), menuResponse.json(), slotResponse.json()]); const loaded = (menu.items ?? []) as TakeawayCatalogItem[]; setConfig(configuration); setItems(loaded); setCategories(menu.categories ?? []); setSlots(slotData.slots ?? []); const selected = findDeepLinkedItem(loaded.filter((item) => item.available), window.location.search); setActive(selected?.category ?? menu.categories?.[0]?.key ?? ""); setCustomizing(selected); }).catch(() => setError(true)); }, []);
  const visible = useMemo(() => active ? items.filter((item) => item.category === active) : items, [active, items]); const asap = slots.find((slot) => slot.type === "asap" && slot.available);
  if (error) return <State title={t({ fr: "La carte n’a pas pu être chargée", en: "The menu could not be loaded", es: "No se pudo cargar la carta", it: "Impossibile caricare il menu" })} body={t({ fr: "Actualisez la page pour réessayer.", en: "Refresh the page to try again.", es: "Actualice la página para volver a intentarlo.", it: "Aggiorna la pagina per riprovare." })}/>;
  if (!config) return <section className="mx-auto max-w-7xl px-6 pb-24 pt-36 md:px-12 lg:px-20"><div className="skeleton h-10 w-52 rounded-xl"/><div className="mt-10 grid gap-5 md:grid-cols-2"><div className="skeleton h-80 rounded-2xl"/><div className="skeleton h-80 rounded-2xl"/></div></section>;
  if (!config.takeaway_enabled || config.pause_mode) return <State title={config.pause_mode ? t({ fr: "Le service fait une pause", en: "Takeaway is taking a short pause", es: "El servicio está en pausa", it: "Il servizio è in pausa" }) : t({ fr: "À emporter est fermé", en: "Takeaway is closed", es: "El servicio para llevar está cerrado", it: "L’asporto è chiuso" })} body={t({ fr: "Votre prochaine commande vous attend bientôt. La carte reste visible au restaurant.", en: "We’ll be ready for your next order soon. You can still explore the restaurant menu.", es: "Pronto estaremos listos para su próximo pedido. Puede consultar la carta del restaurante.", it: "Presto saremo pronti per il tuo prossimo ordine. Puoi consultare il menu del ristorante." })}/>;

  return <>
    <section className="relative overflow-hidden px-6 pb-7 pt-28 md:px-12 md:pb-8 md:pt-28 lg:px-20"><div className="pointer-events-none absolute left-[12%] top-4 h-64 w-64 rounded-full bg-[#7CB895]/[.06] blur-[100px]"/><div className="mx-auto max-w-7xl"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-5xl"><p className="takeaway-kicker">{t({ fr: "À EMPORTER", en: "TAKEAWAY", es: "PARA LLEVAR", it: "DA ASPORTO" })}</p><h1 className="takeaway-display mt-3 max-w-4xl text-[clamp(3.25rem,6vw,6rem)]">{t({ fr: "VOS FAVORIS, PRÊTS À EMPORTER.", en: "YOUR FAVOURITES, READY TO COLLECT.", es: "TUS FAVORITOS, LISTOS PARA RECOGER.", it: "I TUOI PREFERITI, PRONTI AL RITIRO." })}</h1><p className="mt-3 max-w-xl text-sm leading-6 text-fg-muted md:text-base">{t({ fr: "Commandez à l’avance et retirez votre repas au restaurant.", en: "Order ahead and collect from the restaurant.", es: "Pide con antelación y recoge en el restaurante.", it: "Ordina in anticipo e ritira al ristorante." })}</p></div>{cartCount > 0 ? <button onClick={onOpenCart} className="hidden min-h-14 items-center gap-4 rounded-full border border-[#7CB895]/40 bg-[#7CB895]/10 px-6 text-sm text-fg transition hover:border-[#7CB895] md:flex"><span>{added ? t({ fr: "Ajouté à votre commande", en: "Added to your order", es: "Añadido a tu pedido", it: "Aggiunto al tuo ordine" }) : t({ fr: "Votre commande", en: "Your order", es: "Tu pedido", it: "Il tuo ordine" })} · {cartCount}</span><strong className="text-[#F3CDA0]">{formatEuro(cartTotal, lang)}</strong></button> : null}</div><div className="mt-6 flex flex-wrap items-center gap-x-6 gap-y-3 border-y border-theme py-3 text-xs uppercase tracking-[.16em] text-fg-muted"><span className="flex items-center gap-2 text-fg"><i className="h-2 w-2 rounded-full bg-[#7CB895] shadow-[0_0_14px_rgba(124,184,149,.7)]"/>{t({ fr: "Commandes ouvertes", en: "Taking orders now", es: "Aceptando pedidos", it: "Ordini aperti" })}</span>{asap ? <span>{t({ fr: "Premier retrait", en: "Earliest pickup", es: "Primera recogida", it: "Primo ritiro" })}: <strong className="text-fg">{new Intl.DateTimeFormat(lang, { hour: "2-digit", minute: "2-digit", timeZone: "Europe/Paris" }).format(new Date(asap.value))}</strong></span> : null}<span className="rounded-full border border-[#F3CDA0]/30 px-3 py-1 text-[#F3CDA0]">{t({ fr: "RETRAIT UNIQUEMENT", en: "PICKUP ONLY", es: "SOLO RECOGIDA", it: "SOLO RITIRO" })}</span></div></div></section>
    <nav className="sticky top-[72px] z-30 border-y border-theme bg-[var(--nav-bg)] px-6 py-3 backdrop-blur-xl md:px-12 lg:px-20" data-lenis-prevent="true"><div className="mx-auto flex max-w-7xl gap-2 overflow-x-auto">{categories.map((category) => <button key={category.key} onClick={() => setActive(category.key)} className={`min-h-11 whitespace-nowrap rounded-full border px-5 text-xs font-semibold uppercase tracking-[.12em] transition ${active === category.key ? "border-[#7CB895] bg-[#7CB895] text-[#07140d] shadow-[0_0_24px_rgba(124,184,149,.18)]" : "border-theme bg-surface text-fg-muted hover:border-[#7CB895]/60 hover:text-fg"}`}>{category.emoji} {categoryLabel(category, lang, category.key)}</button>)}</div></nav>
    <section className="mx-auto max-w-7xl px-6 py-9 md:px-12 lg:px-20"><div className="grid gap-6 md:grid-cols-2">{visible.map((item) => <article key={item.id} className={`group overflow-hidden rounded-2xl border border-theme bg-surface shadow-[var(--card-shadow)] transition duration-300 ${item.available ? "hover:-translate-y-1 hover:border-[#7CB895]/30" : "opacity-70"}`}><div className="relative aspect-[16/9] overflow-hidden bg-[var(--img-bg)]">{item.image_url ? <Image src={item.image_url} alt={item.name} fill className={`object-cover transition duration-700 ${item.available ? "group-hover:scale-105" : "grayscale"}`} unoptimized/> : <Image src="/images/burger-static.png" alt="" fill className="object-cover opacity-70"/>}<div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/>{!item.available ? <span className="absolute left-4 top-4 rounded-full border border-red-300/30 bg-black/70 px-3 py-1 text-[.65rem] uppercase tracking-[.18em] text-red-200">{t({ fr: "Épuisé", en: "Sold out", es: "Agotado", it: "Esaurito" })}</span> : null}</div><div className="p-5 md:p-6"><div className="flex items-start justify-between gap-5"><h2 className="font-serif text-2xl italic text-fg">{item.name}</h2><strong className="shrink-0 text-sm text-[#F3CDA0]">{formatEuro(Number(item.price), lang)}</strong></div><p className="mt-3 min-h-12 text-sm leading-6 text-fg-muted">{item.description}</p><button disabled={!item.available} onClick={() => setCustomizing(item)} className="mt-5 min-h-12 w-full rounded-xl border border-[#7CB895]/50 px-5 text-xs font-semibold uppercase tracking-[.14em] text-[#7CB895] transition hover:bg-[#7CB895] hover:text-[#07140d] disabled:cursor-not-allowed disabled:border-theme disabled:text-fg-ghost">{item.available ? item.option_groups.length ? t({ fr: "Personnaliser", en: "Customize", es: "Personalizar", it: "Personalizza" }) : t({ fr: "Ajouter", en: "Add", es: "Añadir", it: "Aggiungi" }) : t({ fr: "Indisponible", en: "Unavailable", es: "No disponible", it: "Non disponibile" })}</button></div></article>)}</div>{visible.length === 0 ? <div className="takeaway-panel py-16 text-center"><p className="font-serif text-2xl italic text-fg">{t({ fr: "Rien dans cette catégorie pour le moment.", en: "Nothing in this category just yet.", es: "Todavía no hay nada en esta categoría.", it: "Non c’è ancora nulla in questa categoria." })}</p><p className="mt-2 text-sm text-fg-muted">{t({ fr: "Choisissez une autre catégorie.", en: "Choose another category.", es: "Elige otra categoría.", it: "Scegli un’altra categoria." })}</p></div> : null}</section>
    {customizing ? <TakeawayItemCustomizer item={customizing} onClose={() => setCustomizing(null)} onAdd={(customization) => { onAdd?.(customizing, customization); setCustomizing(null); }}/>: null}
  </>;
}

function State({ title, body }: { title: string; body: string }) { return <section className="grid min-h-[72vh] place-items-center px-6 pt-24 text-center"><div className="max-w-xl"><p className="takeaway-kicker">L’ÉCHOPPE DE PARIS</p><h1 className="takeaway-display mt-4 text-6xl md:text-8xl">{title}</h1><p className="mx-auto mt-5 max-w-md leading-7 text-fg-muted">{body}</p></div></section>; }
