"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { useLang } from "@/context/LangContext";
import type { Category } from "@/lib/hooks/useCategories";
import type { PublicTakeawayConfig, TakeawayCatalogItem } from "@/lib/takeaway/types";
import TakeawayItemCustomizer, { type Customization } from "./TakeawayItemCustomizer";

export default function TakeawayMenu({ onAdd }: { onAdd?: (item: TakeawayCatalogItem, customization: Customization) => void }) {
  const { t, lang } = useLang(); const [config, setConfig] = useState<PublicTakeawayConfig | null>(null); const [items, setItems] = useState<TakeawayCatalogItem[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [active, setActive] = useState(""); const [customizing, setCustomizing] = useState<TakeawayCatalogItem | null>(null);
  useEffect(() => { void Promise.all([fetch("/api/takeaway/config").then((r) => r.json()), fetch("/api/takeaway/menu").then((r) => r.json())]).then(([configuration, menu]) => { setConfig(configuration); setItems(menu.items ?? []); setCategories(menu.categories ?? []); setActive(menu.categories?.[0]?.key ?? ""); }); }, []);
  const visible = useMemo(() => active ? items.filter((item) => item.category === active) : items, [active, items]);
  if (!config) return <p className="p-12 text-center text-fg">{t({ fr: "Chargement…", en: "Loading…", es: "Cargando…", it: "Caricamento…" })}</p>;
  if (!config.takeaway_enabled || config.pause_mode) return <div className="mx-auto max-w-xl p-12 text-center"><h1 className="text-4xl text-fg">{t({ fr: "Commandes momentanément fermées", en: "Ordering is currently closed", es: "Pedidos cerrados temporalmente", it: "Ordini temporaneamente chiusi" })}</h1><p className="mt-3 text-fg/60">{t({ fr: "Revenez bientôt ou contactez le restaurant.", en: "Please check back soon or contact the restaurant.", es: "Vuelva pronto o contacte con el restaurante.", it: "Riprova presto o contatta il ristorante." })}</p></div>;
  return <><nav className="sticky top-20 z-20 flex gap-2 overflow-x-auto border-y border-theme bg-bg/95 p-3" data-lenis-prevent="true">{categories.map((category) => <button key={category.key} onClick={() => setActive(category.key)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${active === category.key ? "bg-fg text-bg" : "bg-surface text-fg"}`}>{category.emoji} {category[lang]}</button>)}</nav><div className="mx-auto grid max-w-6xl gap-5 p-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((item) => <button key={item.id} onClick={() => setCustomizing(item)} className="overflow-hidden rounded-2xl border border-theme bg-surface text-left"><div className="relative h-44 bg-bg">{item.image_url ? <Image src={item.image_url} alt="" fill className="object-cover" unoptimized /> : <div className="grid h-full place-items-center text-5xl">🥡</div>}</div><div className="p-4"><div className="flex justify-between gap-3 text-fg"><strong>{item.name}</strong><span>{Number(item.price).toFixed(2)} €</span></div><p className="mt-2 line-clamp-2 text-sm text-fg/55">{item.description}</p></div></button>)}</div>{visible.length === 0 ? <p className="p-12 text-center text-fg/60">{t({ fr: "Aucun article disponible.", en: "No items available.", es: "No hay artículos disponibles.", it: "Nessun articolo disponibile." })}</p> : null}{customizing ? <TakeawayItemCustomizer item={customizing} onClose={() => setCustomizing(null)} onAdd={(customization) => { onAdd?.(customizing, customization); setCustomizing(null); }} /> : null}</>;
}
