"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import BotCheck from "@/components/BotCheck";
import { useLang } from "@/context/LangContext";
import { useTakeawayCart } from "@/context/TakeawayCartContext";
import TakeawayPickupSlotPicker from "./TakeawayPickupSlotPicker";

type Slot = { value: string; type: "asap" | "scheduled"; available: boolean };
export default function TakeawayCheckoutModal({ onClose }: { onClose: () => void }) { const { t, lang } = useLang(); const cart = useTakeawayCart(); const router = useRouter(); const [slot, setSlot] = useState<Slot | null>(null); const [form, setForm] = useState({ name: "", email: "", phone: "", notes: "", promo: "", website: "" }); const [botOpen, setBotOpen] = useState(false); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); useEffect(() => { document.body.style.overflow = "hidden"; (window as any).lenis?.stop(); return () => { document.body.style.overflow = ""; (window as any).lenis?.start(); }; }, []);
  const submit = async (botToken: string) => { setBotOpen(false); if (!slot) return; setSubmitting(true); setError(""); const response = await fetch("/api/takeaway/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer_name: form.name, customer_email: form.email, customer_phone: form.phone, customer_notes: form.notes, pickup_time_type: slot.type, pickup_time: slot.value, promo_code: form.promo, lang, bot_token: botToken, website: form.website, items: cart.lines.map((line) => ({ item_id: line.item.id, choice_ids: line.choiceIds, special_instructions: line.specialInstructions, quantity: line.quantity })) }) }); const data = await response.json(); if (response.ok) { cart.clear(); router.push(data.tracking_url); } else { setError(data.error ?? "Error"); setSubmitting(false); } };
  const ready = slot && form.name.trim().length >= 2 && form.email.includes("@") && form.phone.trim().length >= 8;
  return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/70 p-4"><section data-lenis-prevent="true" className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-theme bg-surface p-6"><button className="float-right text-fg" onClick={onClose}>×</button><h2 className="text-3xl text-fg">{t({ fr: "Finaliser la commande", en: "Complete your order", es: "Finalizar pedido", it: "Completa l’ordine" })}</h2><div className="mt-5 space-y-4"><TakeawayPickupSlotPicker value={slot} onChange={setSlot} /><div className="grid gap-3 sm:grid-cols-2"><input className="rounded-lg border border-theme bg-bg p-3 text-fg" placeholder={t({ fr: "Nom", en: "Name", es: "Nombre", it: "Nome" })} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className="rounded-lg border border-theme bg-bg p-3 text-fg" type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input className="rounded-lg border border-theme bg-bg p-3 text-fg" type="tel" placeholder={t({ fr: "Téléphone", en: "Phone", es: "Teléfono", it: "Telefono" })} value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input className="rounded-lg border border-theme bg-bg p-3 text-fg" placeholder={t({ fr: "Code promo", en: "Promo code", es: "Código promocional", it: "Codice promo" })} value={form.promo} onChange={(e) => setForm({ ...form, promo: e.target.value })} /></div><textarea maxLength={500} className="w-full rounded-lg border border-theme bg-bg p-3 text-fg" placeholder={t({ fr: "Notes / allergies", en: "Notes / allergies", es: "Notas / alergias", it: "Note / allergie" })} value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><input className="hidden" tabIndex={-1} autoComplete="off" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} /><p className="text-sm text-fg/60">{t({ fr: "Paiement sur place lors du retrait.", en: "Pay onsite when collecting.", es: "Pago en el local al recoger.", it: "Pagamento sul posto al ritiro." })}</p>{error ? <p className="text-sm text-red-400">{error}</p> : null}<button disabled={!ready || submitting} onClick={() => setBotOpen(true)} className="w-full rounded-xl bg-fg p-4 text-bg disabled:opacity-40">{submitting ? t({ fr: "Envoi…", en: "Submitting…", es: "Enviando…", it: "Invio…" }) : `${t({ fr: "Commander", en: "Place order", es: "Pedir", it: "Ordina" })} — ${cart.total.toFixed(2)} €`}</button></div></section>{botOpen ? <BotCheck onPass={(token) => void submit(token)} onClose={() => setBotOpen(false)} /> : null}</div>; }
