import type { Lang } from "@/context/LangContext";

const MAP_URL = "https://google.com/maps?cid=4710868228502671327";
const COPY = {
  fr: { subject: "Confirmation de commande", hello: "Merci pour votre commande", pickup: "Retrait", total: "Total TTC à payer sur place", payment: "Paiement sur place lors du retrait.", track: "Suivre ma commande", directions: "Itinéraire vers le restaurant" },
  en: { subject: "Order confirmation", hello: "Thank you for your order", pickup: "Pickup", total: "Total incl. tax due onsite", payment: "Pay onsite when collecting your order.", track: "Track my order", directions: "Directions to the restaurant" },
  es: { subject: "Confirmación del pedido", hello: "Gracias por su pedido", pickup: "Recogida", total: "Total con impuestos a pagar en el local", payment: "Pago en el local al recoger el pedido.", track: "Seguir mi pedido", directions: "Cómo llegar al restaurante" },
  it: { subject: "Conferma dell’ordine", hello: "Grazie per il tuo ordine", pickup: "Ritiro", total: "Totale IVA inclusa da pagare sul posto", payment: "Pagamento sul posto al ritiro.", track: "Segui il mio ordine", directions: "Indicazioni per il ristorante" },
} satisfies Record<Lang, Record<string, string>>;

const escapeHtml = (value: unknown) => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
type EmailItem = { quantity: number; name: string; options?: string[] };
export function renderOrderConfirmation(input: { lang: Lang; reference: string; pickup: string; total: number; trackingUrl: string; items: EmailItem[] }) { const copy = COPY[input.lang]; const itemText = input.items.map((item) => `${item.quantity}× ${item.name}${item.options?.length ? ` (${item.options.join(", ")})` : ""}`).join("\n"); const text = `${copy.hello} — #${input.reference}\n${copy.pickup}: ${input.pickup}\n${itemText}\n${copy.total}: ${input.total.toFixed(2)} €\n${copy.payment}\n${copy.track}: ${input.trackingUrl}\n${copy.directions}: ${MAP_URL}`; const html = `<main style="font-family:Arial,sans-serif;max-width:600px;margin:auto"><h1>${copy.hello}</h1><h2>#${escapeHtml(input.reference)}</h2><p><strong>${copy.pickup}:</strong> ${escapeHtml(input.pickup)}</p><ul>${input.items.map((item) => `<li>${item.quantity}× ${escapeHtml(item.name)}${item.options?.length ? `<br><small>${item.options.map(escapeHtml).join(", ")}</small>` : ""}</li>`).join("")}</ul><p><strong>${copy.total}: ${input.total.toFixed(2)} €</strong></p><p>${copy.payment}</p><p><a href="${escapeHtml(input.trackingUrl)}">${copy.track}</a> · <a href="${MAP_URL}">${copy.directions}</a></p></main>`; return { subject: `${copy.subject} #${input.reference}`, text, html }; }
