"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { useLang } from "@/context/LangContext";
import { DEFAULT_TAKEAWAY_SETTINGS, type OperatingHours, type PaymentMethod } from "@/lib/takeaway/types";

const METHODS: PaymentMethod[] = ["cash", "card", "ticket_restaurant", "other"];
const DAYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"] as const;

export default function TakeawaySettingsPanel() {
  const { t } = useLang();
  const [settings, setSettings] = useState(DEFAULT_TAKEAWAY_SETTINGS);
  const [state, setState] = useState<"loading" | "ready" | "saving" | "saved" | "error">("loading");
  const [message, setMessage] = useState("");

  useEffect(() => {
    void fetch("/api/admin/takeaway/settings", { cache: "no-store" }).then(async (response) => {
      const data = await response.json();
      if (response.ok && data.settings) { setSettings(data.settings); setState("ready"); return; }
      setMessage(response.status === 401 ? t({ fr: "Votre session a expiré. Reconnectez-vous pour continuer.", en: "Your session has expired. Sign in again to continue.", es: "Tu sesión ha caducado. Inicia sesión de nuevo.", it: "La sessione è scaduta. Accedi di nuovo." }) : t({ fr: "Impossible de charger les paramètres. Réessayez.", en: "Settings could not be loaded. Try again.", es: "No se pudieron cargar los ajustes. Inténtalo de nuevo.", it: "Impossibile caricare le impostazioni. Riprova." }));
      setState("error");
    }).catch(() => { setMessage(t({ fr: "Impossible de charger les paramètres. Réessayez.", en: "Settings could not be loaded. Try again.", es: "No se pudieron cargar los ajustes. Inténtalo de nuevo.", it: "Impossibile caricare le impostazioni. Riprova." })); setState("error"); });
  }, [t]);

  const clientError = useMemo(() => {
    if (!settings.accepted_payment_methods.length) return t({ fr: "Sélectionnez au moins un moyen de paiement sur place.", en: "Select at least one onsite payment method.", es: "Selecciona al menos un método de pago en el local.", it: "Seleziona almeno un metodo di pagamento sul posto." });
    if (settings.max_order_amount > 0 && settings.max_order_amount < settings.min_order_amount) return t({ fr: "Le montant maximum doit être supérieur au montant minimum.", en: "Maximum order amount must be greater than the minimum.", es: "El importe máximo debe superar el mínimo.", it: "L’importo massimo deve superare il minimo." });
    for (const day of DAYS) for (let index = 0; index < settings.operating_hours[day].length; index++) {
      const windows = settings.operating_hours[day]; const current = windows[index];
      if (current.open >= current.close) return `${dayName(day, t)}: ${t({ fr: "la fermeture doit suivre l’ouverture.", en: "closing time must be after opening time.", es: "el cierre debe ser posterior a la apertura.", it: "la chiusura deve seguire l’apertura." })}`;
      if (index > 0 && current.open < windows[index - 1].close) return `${dayName(day, t)}: ${t({ fr: "les plages horaires se chevauchent.", en: "service windows overlap.", es: "las franjas horarias se solapan.", it: "le fasce orarie si sovrappongono." })}`;
    }
    return "";
  }, [settings, t]);

  const save = async () => {
    if (clientError) { setMessage(clientError); setState("error"); return; }
    setState("saving"); setMessage("");
    try {
      const response = await fetch("/api/admin/takeaway/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); const data = await response.json();
      if (!response.ok) { setMessage(data.error || t({ fr: "Enregistrement impossible. Corrigez le champ indiqué.", en: "Could not save. Correct the indicated field.", es: "No se pudo guardar. Corrige el campo indicado.", it: "Impossibile salvare. Correggi il campo indicato." })); setState("error"); return; }
      setSettings(data.settings); setMessage(t({ fr: "Paramètres enregistrés.", en: "Settings saved.", es: "Ajustes guardados.", it: "Impostazioni salvate." })); setState("saved");
    } catch { setMessage(t({ fr: "Connexion interrompue. Vos modifications sont conservées ici.", en: "Connection interrupted. Your changes are still preserved here.", es: "Conexión interrumpida. Tus cambios siguen aquí.", it: "Connessione interrotta. Le modifiche restano qui." })); setState("error"); }
  };
  const changeWindow = (day: keyof OperatingHours, index: number, field: "open" | "close", value: string) => setSettings((current) => ({ ...current, operating_hours: { ...current.operating_hours, [day]: current.operating_hours[day].map((window, position) => position === index ? { ...window, [field]: value } : window) } }));
  const numeric = (key: "closing_cutoff_minutes" | "prep_lead_time_minutes" | "slot_interval_minutes" | "advance_order_max_days" | "max_orders_per_slot" | "min_order_amount" | "max_order_amount", label: string) => <label className="rounded-xl border border-white/8 bg-black/20 p-4 text-xs text-white/55"><span className="font-medium text-white/80">{label}</span><input className="mt-2 w-full rounded-lg border border-white/10 bg-black/30 p-2.5 text-white outline-none focus:border-[#7CB895]" type="number" min={key === "slot_interval_minutes" ? 1 : 0} step={key.includes("amount") ? ".01" : "1"} value={settings[key]} onChange={(event) => setSettings((current) => ({ ...current, [key]: Number(event.target.value) }))}/></label>;

  if (state === "loading") return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-8 text-sm text-white/50">{t({ fr: "Chargement des paramètres…", en: "Loading settings…", es: "Cargando ajustes…", it: "Caricamento impostazioni…" })}</section>;
  return <section className="space-y-6">
    <Section title={t({ fr: "État du service", en: "Service status", es: "Estado del servicio", it: "Stato del servizio" })} note={t({ fr: "Activation et pause opérationnelle immédiate.", en: "Immediate operational activation and pause.", es: "Activación y pausa operativa inmediatas.", it: "Attivazione e pausa immediate." })}><div className="grid gap-3 md:grid-cols-3">{(["takeaway_enabled", "pause_mode", "audio_alert_enabled"] as const).map((key) => <label key={key} className="flex min-h-16 items-center gap-3 rounded-xl border border-white/10 bg-black/20 px-4 text-sm text-white/80"><input type="checkbox" checked={settings[key]} onChange={() => setSettings((current) => ({ ...current, [key]: !current[key] }))}/>{key === "takeaway_enabled" ? t({ fr: "Commandes activées", en: "Ordering enabled", es: "Pedidos activados", it: "Ordini attivi" }) : key === "pause_mode" ? t({ fr: "Service en pause", en: "Pause service", es: "Pausar servicio", it: "Metti in pausa" }) : t({ fr: "Alertes sonores", en: "Audio alerts", es: "Alertas sonoras", it: "Avvisi sonori" })}</label>)}</div></Section>
    <Section title={t({ fr: "Préparation et créneaux", en: "Preparation and pickup slots", es: "Preparación y franjas", it: "Preparazione e fasce" })} note={t({ fr: "Les règles serveur de capacité et de coupure restent autoritaires.", en: "Server capacity and cutoff rules remain authoritative.", es: "Las reglas del servidor siguen siendo autoritativas.", it: "Le regole server restano autorevoli." })}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{numeric("prep_lead_time_minutes", t({ fr: "Préparation (min)", en: "Preparation (min)", es: "Preparación (min)", it: "Preparazione (min)" }))}{numeric("closing_cutoff_minutes", t({ fr: "Coupure (min)", en: "Closing cutoff (min)", es: "Margen de cierre (min)", it: "Margine chiusura (min)" }))}{numeric("slot_interval_minutes", t({ fr: "Intervalle (min)", en: "Slot interval (min)", es: "Intervalo (min)", it: "Intervallo (min)" }))}{numeric("max_orders_per_slot", t({ fr: "Capacité par créneau", en: "Capacity per slot", es: "Capacidad por franja", it: "Capacità per fascia" }))}</div></Section>
    <Section title={t({ fr: "Limites de commande", en: "Order limits", es: "Límites del pedido", it: "Limiti ordine" })} note={t({ fr: "Montants TTC expliqués au client avant validation.", en: "TTC amounts explained before checkout.", es: "Importes con impuestos explicados antes del checkout.", it: "Importi IVA inclusa spiegati prima del checkout." })}><div className="grid gap-3 md:grid-cols-3">{numeric("min_order_amount", t({ fr: "Minimum (€ TTC)", en: "Minimum (€ incl. tax)", es: "Mínimo (€ imp. incl.)", it: "Minimo (€ IVA incl.)" }))}{numeric("max_order_amount", t({ fr: "Maximum (€ TTC)", en: "Maximum (€ incl. tax)", es: "Máximo (€ imp. incl.)", it: "Massimo (€ IVA incl.)" }))}{numeric("advance_order_max_days", t({ fr: "Jours à l’avance", en: "Advance-order days", es: "Días de antelación", it: "Giorni di anticipo" }))}</div></Section>
    <Section title={t({ fr: "Paiement sur place", en: "Onsite payment", es: "Pago en el local", it: "Pagamento sul posto" })} note={t({ fr: "Aucun paiement en ligne. Ces méthodes apparaissent au client.", en: "No online payment. These methods are shown to the customer.", es: "Sin pago online. Estos métodos se muestran al cliente.", it: "Nessun pagamento online. Questi metodi sono mostrati al cliente." })}><div className="flex flex-wrap gap-3">{METHODS.map((method) => <label key={method} className="flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-black/20 px-4 text-sm text-white/75"><input type="checkbox" checked={settings.accepted_payment_methods.includes(method)} onChange={() => setSettings((current) => ({ ...current, accepted_payment_methods: current.accepted_payment_methods.includes(method) ? current.accepted_payment_methods.filter((value) => value !== method) : [...current.accepted_payment_methods, method] }))}/>{methodName(method, t)}</label>)}</div></Section>
    <Section title={t({ fr: "Horaires de retrait", en: "Pickup hours", es: "Horarios de recogida", it: "Orari di ritiro" })} note={t({ fr: "Plusieurs services par jour, sans chevauchement.", en: "Multiple services per day, without overlap.", es: "Varios servicios al día, sin solaparse.", it: "Più servizi al giorno, senza sovrapposizioni." })}><div className="space-y-3">{DAYS.map((day) => <div key={day} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between"><strong className="text-sm text-white/85">{dayName(day, t)}</strong><button className="rounded-lg border border-white/10 px-3 py-2 text-xs text-[#9dd4b5]" onClick={() => setSettings((current) => ({ ...current, operating_hours: { ...current.operating_hours, [day]: [...current.operating_hours[day], { open: "12:00", close: "14:00" }] } }))}>+ {t({ fr: "Ajouter un service", en: "Add service", es: "Añadir servicio", it: "Aggiungi servizio" })}</button></div>{settings.operating_hours[day].length ? <div className="mt-3 grid gap-2">{settings.operating_hours[day].map((window, index) => <div key={index} className="flex flex-wrap items-center gap-2"><input aria-label={`${dayName(day, t)} ${t({ fr: "ouverture", en: "opening", es: "apertura", it: "apertura" })}`} type="time" value={window.open} onChange={(event) => changeWindow(day, index, "open", event.target.value)} className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-white outline-none focus:border-[#7CB895]"/><span className="text-white/30">→</span><input aria-label={`${dayName(day, t)} ${t({ fr: "fermeture", en: "closing", es: "cierre", it: "chiusura" })}`} type="time" value={window.close} onChange={(event) => changeWindow(day, index, "close", event.target.value)} className="rounded-lg border border-white/10 bg-black/30 p-2.5 text-white outline-none focus:border-[#7CB895]"/><button aria-label={t({ fr: "Supprimer la plage", en: "Remove window", es: "Eliminar franja", it: "Rimuovi fascia" })} className="grid h-10 w-10 place-items-center rounded-lg text-red-300" onClick={() => setSettings((current) => ({ ...current, operating_hours: { ...current.operating_hours, [day]: current.operating_hours[day].filter((_, position) => position !== index) } }))}>×</button></div>)}</div> : <p className="mt-3 text-xs text-white/35">{t({ fr: "Fermé", en: "Closed", es: "Cerrado", it: "Chiuso" })}</p>}</div>)}</div></Section>
    {(message || clientError) ? <p role={state === "saved" && !clientError ? "status" : "alert"} className={`rounded-xl border p-4 text-sm ${state === "saved" && !clientError ? "border-[#7CB895]/25 bg-[#7CB895]/10 text-[#9dd4b5]" : "border-red-400/20 bg-red-400/5 text-red-300"}`}>{clientError || message}</p> : null}
    <div className="flex justify-end"><button onClick={() => void save()} disabled={state === "saving" || Boolean(clientError)} className="min-h-12 rounded-xl bg-[#7CB895] px-7 text-sm font-semibold text-[#07140d] disabled:cursor-not-allowed disabled:opacity-45">{state === "saving" ? t({ fr: "Enregistrement…", en: "Saving…", es: "Guardando…", it: "Salvataggio…" }) : t({ fr: "Enregistrer les paramètres", en: "Save settings", es: "Guardar ajustes", it: "Salva impostazioni" })}</button></div>
  </section>;
}

function Section({ title, note, children }: { title: string; note: string; children: ReactNode }) { return <section className="rounded-2xl border border-white/10 bg-white/[.035] p-5 md:p-6"><h2 className="text-lg font-semibold text-white">{title}</h2><p className="mb-5 mt-1 text-sm text-white/40">{note}</p>{children}</section>; }
function dayName(day: string, t: ReturnType<typeof useLang>["t"]) { return ({ monday: t({ fr: "Lundi", en: "Monday", es: "Lunes", it: "Lunedì" }), tuesday: t({ fr: "Mardi", en: "Tuesday", es: "Martes", it: "Martedì" }), wednesday: t({ fr: "Mercredi", en: "Wednesday", es: "Miércoles", it: "Mercoledì" }), thursday: t({ fr: "Jeudi", en: "Thursday", es: "Jueves", it: "Giovedì" }), friday: t({ fr: "Vendredi", en: "Friday", es: "Viernes", it: "Venerdì" }), saturday: t({ fr: "Samedi", en: "Saturday", es: "Sábado", it: "Sabato" }), sunday: t({ fr: "Dimanche", en: "Sunday", es: "Domingo", it: "Domenica" }) }[day] ?? day); }
function methodName(method: PaymentMethod, t: ReturnType<typeof useLang>["t"]) { return ({ cash: t({ fr: "Espèces", en: "Cash", es: "Efectivo", it: "Contanti" }), card: t({ fr: "Carte", en: "Card", es: "Tarjeta", it: "Carta" }), ticket_restaurant: t({ fr: "Titres restaurant", en: "Meal vouchers", es: "Vales de comida", it: "Buoni pasto" }), other: t({ fr: "Autre", en: "Other", es: "Otro", it: "Altro" }) }[method]); }
