"use client";

import { useCallback, useEffect, useState } from "react";
import { createClient } from "@/lib/postgres/client";
import type { MenuItem } from "@/lib/postgres/types";
import type { TakeawayOptionGroup } from "@/lib/takeaway/types";
import { useLang } from "@/context/LangContext";
type GroupLink = { item_id: string; group_id: string; display_order: number };

export default function TakeawayMenuManager() {
  const { t, lang } = useLang(); const [items, setItems] = useState<MenuItem[]>([]); const [groups, setGroups] = useState<TakeawayOptionGroup[]>([]); const [links, setLinks] = useState<GroupLink[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const db = createClient(); const [a, b, c] = await Promise.all([db.from("menu_items").select("*").order("display_order"), db.from("takeaway_option_groups").select("*").order("display_order"), db.from("menu_item_option_groups").select("*").order("display_order")]); setItems(a.data ?? []); setGroups(b.data ?? []); setLinks(c.data ?? []); }, []); useEffect(() => { void load(); }, [load]);
  const update = async (item: MenuItem, values: Partial<MenuItem>) => { if (values.takeaway_available && (values.vat_rate ?? item.vat_rate) == null) { setMessage(t({ fr: "Attribuez un taux de TVA avant d’activer cet article.", en: "Assign a VAT rate before enabling this item.", es: "Asigne un IVA antes de activar este artículo.", it: "Assegna un’aliquota IVA prima di attivare l’articolo." })); return; } const { error } = await createClient().from("menu_items").update(values).eq("id", item.id); setMessage(error?.message ?? ""); await load(); };
  const toggleLink = async (itemId: string, groupId: string) => { const db = createClient(); const existing = links.find((link) => link.item_id === itemId && link.group_id === groupId); if (existing) await db.from("menu_item_option_groups").delete().eq("item_id", itemId).eq("group_id", groupId); else await db.from("menu_item_option_groups").insert({ item_id: itemId, group_id: groupId, display_order: links.filter((link) => link.item_id === itemId).length }); await load(); };
  const orderLink = async (itemId: string, groupId: string, displayOrder: number) => { await createClient().from("menu_item_option_groups").update({ display_order: Math.max(0, displayOrder) }).eq("item_id", itemId).eq("group_id", groupId); await load(); };
  return <section className="rounded-2xl border border-theme bg-surface p-5"><h2 className="text-2xl text-fg">{t({ fr: "Catalogue Takeaway", en: "Takeaway catalog", es: "Catálogo para llevar", it: "Catalogo asporto" })}</h2>{message ? <p className="my-3 text-sm text-red-400">{message}</p> : null}<div className="mt-4 space-y-3">{items.map((item) => <article key={item.id} className="rounded-xl border border-theme bg-bg p-4"><div className="grid items-end gap-3 md:grid-cols-[1fr_120px_130px_100px]"><div><strong className="text-fg">{item.name}</strong><p className="text-xs text-fg/45">{item.category}</p></div><label className="text-xs text-fg/60">{t({ fr: "TVA %", en: "VAT %", es: "IVA %", it: "IVA %" })}<input className="mt-1 w-full rounded border border-theme bg-surface p-2 text-fg" type="number" min="0" max="99.99" step=".01" value={item.vat_rate ?? ""} onChange={(event) => void update(item, { vat_rate: event.target.value === "" ? null : Number(event.target.value), ...(event.target.value === "" ? { takeaway_available: false } : {}) })} /></label><label className="text-xs text-fg/60">{t({ fr: "Quantité maximale (0 = illimitée)", en: "Maximum quantity (0 = unlimited)", es: "Cantidad máxima (0 = ilimitada)", it: "Quantità massima (0 = illimitata)" })}<input className="mt-1 w-full rounded border border-theme bg-surface p-2 text-fg" type="number" min="0" value={item.max_quantity_per_order} onChange={(event) => void update(item, { max_quantity_per_order: Number(event.target.value) })} /></label><label className="text-xs text-fg/60">{t({ fr: "Ordre", en: "Order", es: "Orden", it: "Ordine" })}<input className="mt-1 w-full rounded border border-theme bg-surface p-2 text-fg" type="number" min="0" value={item.display_order} onChange={(event) => void update(item, { display_order: Number(event.target.value) })} /></label></div><div className="mt-3 flex flex-wrap gap-3"><label className="text-sm text-fg"><input className="mr-2" type="checkbox" checked={item.takeaway_available} onChange={(event) => void update(item, { takeaway_available: event.target.checked })} />{t({ fr: "Disponible à emporter", en: "Takeaway available", es: "Disponible para llevar", it: "Disponibile da asporto" })}</label>{groups.map((group) => { const link = links.find((value) => value.item_id === item.id && value.group_id === group.id); return <span key={group.id} className="text-xs text-fg/60"><label><input className="mr-1" type="checkbox" checked={Boolean(link)} onChange={() => void toggleLink(item.id, group.id)} />{group.name[lang]}</label>{link ? <input aria-label={t({ fr: "Ordre du groupe", en: "Group order", es: "Orden del grupo", it: "Ordine del gruppo" })} className="ml-1 w-12 rounded bg-surface px-1" type="number" min="0" value={link.display_order} onChange={(event) => void orderLink(item.id, group.id, Number(event.target.value))} /> : null}</span>; })}</div></article>)}</div></section>;
}
