"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { useLang, type Lang } from "@/context/LangContext";
import type { OrderStatus } from "@/lib/takeaway/types";
import { formatEuro } from "@/lib/takeaway/format";

type TrackedOrder = { order_reference: string; pickup_time: string; status: OrderStatus; payment_status: string; final_total_ttc: number; can_cancel: boolean; items: { quantity: number; name: string; selected_options?: { choice_name: Record<string, string> }[] }[] };
const STEPS: OrderStatus[] = ["NEW", "ACCEPTED", "PREPARING", "READY", "COMPLETED"]; const LANGUAGES: Lang[] = ["fr", "en", "es", "it"];

export default function TrackingPage() {
  const { token } = useParams<{ token: string }>(); const { t, lang, setLang } = useLang(); const [order, setOrder] = useState<TrackedOrder | null>(null); const [missing, setMissing] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/takeaway/orders/${token}`, { cache: "no-store" }); if (response.status === 404) { setMissing(true); return; } if (!response.ok) return; setMissing(false); setOrder((await response.json()).order); }, [token]); useEffect(() => { void load(); const timer = setInterval(() => void load(), 8000); return () => clearInterval(timer); }, [load]);
  const cancel = async () => { if (!confirm(t({ fr: "Annuler cette commande ?", en: "Cancel this order?", es: "¿Cancelar este pedido?", it: "Annullare questo ordine?" }))) return; await fetch(`/api/takeaway/orders/${token}/cancel`, { method: "POST" }); await load(); };
  const statusLabel = (status: OrderStatus) => ({ NEW: t({ fr: "Commande reçue", en: "Order received", es: "Pedido recibido", it: "Ordine ricevuto" }), ACCEPTED: t({ fr: "Commande acceptée", en: "Order accepted", es: "Pedido aceptado", it: "Ordine accettato" }), PREPARING: t({ fr: "En préparation", en: "Preparing", es: "En preparación", it: "In preparazione" }), READY: t({ fr: "Prête au retrait", en: "Ready for pickup", es: "Lista para recoger", it: "Pronto per il ritiro" }), COMPLETED: t({ fr: "Commande retirée", en: "Collected", es: "Pedido recogido", it: "Ordine ritirato" }), CANCELLED: t({ fr: "Commande annulée", en: "Order cancelled", es: "Pedido cancelado", it: "Ordine annullato" }), NO_SHOW: t({ fr: "Commande non retirée", en: "Order not collected", es: "Pedido no recogido", it: "Ordine non ritirato" }) }[status]);
  if (missing) return <main className="grid min-h-screen place-items-center bg-bg p-6 text-center text-fg"><div><h1 className="text-4xl">{t({ fr: "Commande introuvable", en: "Order not found", es: "Pedido no encontrado", it: "Ordine non trovato" })}</h1><Link href="/takeaway">← {t({ fr: "À emporter", en: "Takeaway", es: "Para llevar", it: "Da asporto" })}</Link></div></main>;
  if (!order) return <main className="grid min-h-screen place-items-center bg-bg text-fg">{t({ fr: "Chargement…", en: "Loading…", es: "Cargando…", it: "Caricamento…" })}</main>;
  const terminal = order.status === "CANCELLED" || order.status === "NO_SHOW";
  return <main className="min-h-screen bg-bg p-6 text-fg"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><Link href="/takeaway">← {t({ fr: "À emporter", en: "Takeaway", es: "Para llevar", it: "Da asporto" })}</Link><div className="flex gap-2">{LANGUAGES.map((value) => <button key={value} onClick={() => setLang(value)} className={lang === value ? "text-fg" : "text-fg/40"}>{value.toUpperCase()}</button>)}</div></div><section className={`mt-8 rounded-3xl border p-6 ${terminal ? "border-red-500/40 bg-red-500/5" : "border-theme bg-surface"}`}><p className="text-fg/50">{t({ fr: "Commande", en: "Order", es: "Pedido", it: "Ordine" })}</p><h1 className="text-4xl">#{order.order_reference}</h1><p className="mt-2">{new Date(order.pickup_time).toLocaleString(lang, { timeZone: "Europe/Paris" })}</p>{terminal ? <div className="my-8 rounded-xl border border-red-500/30 p-4 text-red-300"><strong>{statusLabel(order.status)}</strong><p className="mt-1 text-sm">{order.status === "CANCELLED" ? t({ fr: "Cette commande ne sera pas préparée.", en: "This order will not be prepared.", es: "Este pedido no se preparará.", it: "Questo ordine non sarà preparato." }) : t({ fr: "Contactez le restaurant si vous avez besoin d’aide.", en: "Contact the restaurant if you need help.", es: "Contacte con el restaurante si necesita ayuda.", it: "Contatta il ristorante se hai bisogno di assistenza." })}</p></div> : <><div className="my-8 flex justify-between gap-1">{STEPS.map((step) => <div key={step} className={`h-2 flex-1 rounded ${STEPS.indexOf(step) <= STEPS.indexOf(order.status) ? "bg-fg" : "bg-bg"}`} title={statusLabel(step)} />)}</div><p className="text-xl">{statusLabel(order.status)}</p></>}<ul className="my-5 space-y-2">{order.items.map((item, index) => <li key={index}>{item.quantity}× {item.name}<small className="block text-fg/50">{item.selected_options?.map((option) => option.choice_name[lang]).join(", ")}</small></li>)}</ul><p className="text-2xl">{formatEuro(Number(order.final_total_ttc), lang)}</p><p className="text-sm text-fg/60">{t({ fr: "À régler sur place", en: "Pay onsite", es: "Pago en el local", it: "Pagamento sul posto" })}</p>{order.can_cancel ? <button onClick={() => void cancel()} className="mt-5 rounded-xl border border-red-500 px-4 py-3 text-red-400">{t({ fr: "Annuler ma commande", en: "Cancel my order", es: "Cancelar mi pedido", it: "Annulla il mio ordine" })}</button> : null}</section></div></main>;
}
