"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { useLang } from "@/context/LangContext";
import type { OrderStatus } from "@/lib/takeaway/types";

type TrackedOrder = { order_reference: string; pickup_time: string; status: OrderStatus; payment_status: string; final_total_ttc: number; can_cancel: boolean; items: { quantity: number; name: string; selected_options?: { choice_name: Record<string, string> }[] }[] };
const STEPS: OrderStatus[] = ["NEW", "ACCEPTED", "PREPARING", "READY", "COMPLETED"];
export default function TrackingPage() { const { token } = useParams<{ token: string }>(); const { t, lang } = useLang(); const [order, setOrder] = useState<TrackedOrder | null>(null); const [missing, setMissing] = useState(false); const load = useCallback(async () => { const response = await fetch(`/api/takeaway/orders/${token}`, { cache: "no-store" }); if (!response.ok) { setMissing(true); return; } setOrder((await response.json()).order); }, [token]); useEffect(() => { void load(); const timer = setInterval(() => void load(), 8000); return () => clearInterval(timer); }, [load]); const cancel = async () => { if (!confirm(t({ fr: "Annuler cette commande ?", en: "Cancel this order?", es: "¿Cancelar este pedido?", it: "Annullare questo ordine?" }))) return; await fetch(`/api/takeaway/orders/${token}/cancel`, { method: "POST" }); await load(); };
  if (missing) return <main className="grid min-h-screen place-items-center bg-bg p-6 text-center text-fg"><div><h1 className="text-4xl">{t({ fr: "Commande introuvable", en: "Order not found", es: "Pedido no encontrado", it: "Ordine non trovato" })}</h1><Link href="/takeaway">← Takeaway</Link></div></main>;
  if (!order) return <main className="grid min-h-screen place-items-center bg-bg text-fg">{t({ fr: "Chargement…", en: "Loading…", es: "Cargando…", it: "Caricamento…" })}</main>;
  return <main className="min-h-screen bg-bg p-6 text-fg"><div className="mx-auto max-w-2xl"><Link href="/takeaway">← Takeaway</Link><section className="mt-8 rounded-3xl border border-theme bg-surface p-6"><p className="text-fg/50">{t({ fr: "Commande", en: "Order", es: "Pedido", it: "Ordine" })}</p><h1 className="text-4xl">#{order.order_reference}</h1><p className="mt-2">{new Date(order.pickup_time).toLocaleString(lang, { timeZone: "Europe/Paris" })}</p><div className="my-8 flex justify-between gap-1">{STEPS.map((step) => <div key={step} className={`h-2 flex-1 rounded ${STEPS.indexOf(step) <= STEPS.indexOf(order.status) ? "bg-fg" : "bg-bg"}`} title={step} />)}</div><p className="text-xl">{order.status}</p><ul className="my-5 space-y-2">{order.items.map((item, index) => <li key={index}>{item.quantity}× {item.name}<small className="block text-fg/50">{item.selected_options?.map((option) => option.choice_name[lang]).join(", ")}</small></li>)}</ul><p className="text-2xl">{Number(order.final_total_ttc).toFixed(2)} € TTC</p><p className="text-sm text-fg/60">{t({ fr: "À régler sur place", en: "Pay onsite", es: "Pago en el local", it: "Pagamento sul posto" })}</p>{order.can_cancel ? <button onClick={() => void cancel()} className="mt-5 rounded-xl border border-red-500 px-4 py-3 text-red-400">{t({ fr: "Annuler ma commande", en: "Cancel my order", es: "Cancelar mi pedido", it: "Annulla il mio ordine" })}</button> : null}</section></div></main>;
}
